import tkinter as tk
import random
import supabase

# Initialize Supabase credentials
SUPABASE_URL = 'https://your-project-id.supabase.co'
SUPABASE_KEY = 'your-anon-key'
supabase_client = supabase.create_client(SUPABASE_URL, SUPABASE_KEY)

class CatchTheBallGame:
        def __init__(self, root):
                    self.root = root
                            self.root.title("Catch the Ball Game")

                                    self.canvas = tk.Canvas(root, width=500, height=400, bg='lightblue')
                                            self.canvas.pack()

                                                    self.paddle = self.canvas.create_rectangle(225, 350, 275, 360, fill='blue')
                                                            self.ball = self.canvas.create_oval(10, 10, 30, 30, fill='red')

                                                                    self.canvas.bind('<Motion>', self.move_paddle)
                                                                            
                                                                                    self.ball_x = random.randint(1, 3)
                                                                                            self.ball_y = random.randint(1, 3)
                                                                                                    self.score = 0
                                                                                                            self.lives = 3
                                                                                                                    
                                                                                                                            self.score_text = self.canvas.create_text(450, 20, text=f'Score: {self.score}', font=('Arial', 16))
                                                                                                                                    self.lives_text = self.canvas.create_text(50, 20, text=f'Lives: {self.lives}', font=('Arial', 16))
                                                                                                                                            
                                                                                                                                                    self.update_ball()
                                                                                                                                                            
                                                                                                                                                                def move_paddle(self, event):
                                                                                                                                                                            paddle_width = self.canvas.coords(self.paddle)[2] - self.canvas.coords(self.paddle)[0]
                                                                                                                                                                                    self.canvas.coords(self.paddle, event.x - paddle_width / 2, 350, event.x + paddle_width / 2, 360)
                                                                                                                                                                                        
                                                                                                                                                                                            def update_ball(self):
                                                                                                                                                                                                        self.canvas.move(self.ball, self.ball_x, self.ball_y)
                                                                                                                                                                                                                ball_pos = self.canvas.coords(self.ball)
                                                                                                                                                                                                                        paddle_pos = self.canvas.coords(self.paddle)
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        if ball_pos[1] <= 0 or ball_pos[3] >= self.canvas.winfo_height():
                                                                                                                                                                                                                                                        self.ball_y = -self.ball_y
                                                                                                                                                                                                                                                                if ball_pos[0] <= 0 or ball_pos[2] >= self.canvas.winfo_width():
                                                                                                                                                                                                                                                                                self.ball_x = -self.ball_x
                                                                                                                                                                                                                                                                                        if self.intersect(ball_pos, paddle_pos):
                                                                                                                                                                                                                                                                                                        self.ball_y = -self.ball_y
                                                                                                                                                                                                                                                                                                                    self.score += 1
                                                                                                                                                                                                                                                                                                                                self.canvas.itemconfig(self.score_text, text=f'Score: {self.score}')
                                                                                                                                                                                                                                                                                                                                        if ball_pos[3] >= self.canvas.winfo_height():
                                                                                                                                                                                                                                                                                                                                                        self.lives -= 1
                                                                                                                                                                                                                                                                                                                                                                    self.canvas.itemconfig(self.lives_text, text=f'Lives: {self.lives}')
                                                                                                                                                                                                                                                                                                                                                                                self.canvas.coords(self.ball, 10, 10, 30, 30)
                                                                                                                                                                                                                                                                                                                                                                                            if self.lives == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                self.game_over()
                                                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                        self.root.after(20, self.update_ball)
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                def intersect(self, ball, paddle):
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (ball[2] >= paddle[0] and ball[0] <= paddle[2]) and (ball[3] >= paddle[1] and ball[1] <= paddle[3])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def game_over(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.canvas.create_text(250, 200, text='Game Over', font=('Arial', 24), fill='red')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Save score to Supabase database
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.save_score_to_supabase()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.root.after(2000, self.root.destroy)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def save_score_to_supabase(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Save score to Supabase 'scores' table
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    insert_query = supabase_client.from_table('scores').insert({'score': self.score})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            supabase_client.execute(insert_query)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Score {self.score} saved to Supabase.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    root = tk.Tk()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        game = CatchTheBallGame(root)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            root.mainloop()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            